---
- name: Install nfs server
  apt:
    name:
      - nfs-kernel-server
    state: present

- name: Create directory to hold homes
  ansible.builtin.file:
    path: "{{ nfs_remote_homes }}"
    state: directory

- name: Install exports file
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: reload nfs exports

- name: Install nfsd threads conf file
  ansible.builtin.template:
    src: nfsd-threads.conf.j2
    dest: /etc/nfs.conf.d/nfsd-threads.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nfs server

- name: Nfs server running
  ansible.builtin.service:
    name: nfs-kernel-server
    state: started
    enabled: true
