---
roles:
  - name: osc.open_ondemand
    version: "v3.1.5"

collections:
  - name: community.general
    version: 8.1.0
    type: galaxy
  - name: amazon.aws
    version: 7.0.0
    type: galaxy
  - name: community.crypto
    version: 2.16.1
    type: galaxy
  - name: ansible.posix
    version: 1.5.4
    type: galaxy
  - name: prometheus.prometheus
    version: 0.16.3
    type: galaxy
