---
roles:
  - name: osc.open_ondemand
    version: "v3.1.5"

collections:
  - name: community.general
    version: 8.1.0
    type: galaxy
  - name: amazon.aws
    version: 9.4.0
    type: galaxy
  - name: community.crypto
    type: galaxy
  - name: ansible.posix
    type: galaxy
  - name: prometheus.prometheus
    type: galaxy
  - name: grafana.grafana
    version: 5.7.0
    type: galaxy
  - name: community.grafana
    type: galaxy
