---
- name: Create ondemand_exporter group
  ansible.builtin.group:
    name: ondemand_exporter
    state: present
    system: true

- name: Create ondemand_exporter user
  ansible.builtin.user:
    name: ondemand_exporter
    group: ondemand_exporter
    shell: /sbin/nologin
    home: /var/lib/ondemand_exporter
    system: true
    create_home: false

- name: Download ondemand_exporter binary
  ansible.builtin.get_url:
    url: "https://github.com/OSC/ondemand_exporter/releases/download/v{{ ondemand_exporter_version }}/ondemand_exporter-{{ ondemand_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/ondemand_exporter-{{ ondemand_exporter_version }}.tar.gz"
    checksum: "{{ ondemand_exporter_checksum }}"

- name: Extract ondemand_exporter binary
  ansible.builtin.unarchive:
    src: "/tmp/ondemand_exporter-{{ ondemand_exporter_version }}.tar.gz"
    dest: /tmp
    extra_opts:
      - --strip-components
      - 1
    remote_src: true
    creates: /tmp/ondemand_exporter

- name: Install ondemand_exporter binary
  ansible.builtin.copy:
    src: /tmp/ondemand_exporter
    dest: /usr/local/bin/ondemand_exporter
    remote_src: true
    owner: root
    group: root
    mode: 0755

- name: Install ondemand_exporter sudo rule
  ansible.builtin.copy:
    src: ondemand_exporter_sudo
    dest: /etc/sudoers.d/ondemand_exporter
    mode: 0440

- name: Install Apache config for ondemand_exporter
  ansible.builtin.copy:
    src: ondemand_exporter_apache.conf
    dest: /etc/apache2/mods-available/status.conf
  notify: Restart httpd

- name: Enable apache mod_status module
  ansible.builtin.command:
    cmd: a2enmod status.load
    creates: /etc/apache2/mods-enabled/status.load
  notify: Restart httpd

- name: Enable apache ondemand_exporter conf
  ansible.builtin.command:
    cmd: a2enmod status.conf
    creates: /etc/apache2/mods-enabled/status.conf
  notify: Restart httpd

- name: Install ondemand_exporter systemd unit file
  ansible.builtin.copy:
    src: ondemand_exporter.service
    dest: /etc/systemd/system/ondemand_exporter.service
  notify:
    - Reload systemd

- name: Flush handlers
  meta: flush_handlers

- name: Start ondemand_exporter service
  ansible.builtin.systemd:
    name: ondemand_exporter
    state: started
    enabled: true

