---
- name: Clone kube-prometheus
  ansible.builtin.git:
    repo: "https://github.com/prometheus-operator/kube-prometheus.git"
    dest: /opt/kube-prometheus
    version: "{{ kube_prometheus_version }}"
    force: true

- name: Configure remote write
  ansible.builtin.blockinfile:
    path: /opt/kube-prometheus/manifests/prometheus-prometheus.yaml
    block: |
      {% filter indent(width=2, first=true) %}
      remoteWrite:
        - url: 'http://{{ hostvars["servicesnode"]["ansible_default_ipv4"]["address"] }}:9090/api/v1/write'
      {% endfilter %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK"

- name: Setup kube-prometheus
  ansible.builtin.shell:
    chdir: /opt/kube-prometheus
    cmd: kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig apply --server-side -f manifests/setup

- name: Wait for setup to complete
  ansible.builtin.shell:
    cmd: kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig wait --for condition=Established --all CustomResourceDefinition --namespace=monitoring

- name: Install kube-prometheus
  ansible.builtin.shell:
    chdir: /opt/kube-prometheus
    cmd: kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig apply -f manifests/
