---
- name: Run node exporter ansible role
  ansible.builtin.include_role:
    name: prometheus.prometheus.node_exporter
  vars:
    node_exporter_version: "{{ version_node_exporter }}"
    node_exporter_enabled_collectors:
      - systemd
      - processes
      - mountstats
